feat: Update `cozy-ui` dependency to v70.5.1
cozy/mespapiers pull request #294
Opened 2022-08-09 08:52 UTC by PolariTOON

2022-08-09 08:54 UTC, PolariTOON commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bug - dans le viewer au niveau du titre date pour les documents de type "Autres" -> Viewer.panel.qualification.date.title.date](https://trello.com/c/O2h0N8Or/936-bug-dans-le-viewer-au-niveau-du-titre-date-pour-les-documents-de-type-autres-viewerpanelqualificationdatetitledate)

2022-08-09 12:18 UTC, Merkur39 approved these changes
Penser à mettre également à jour `cozy-mespapiers-lib` (dans la version suivant le merge de https://github.com/cozy/cozy-libs/pull/1791) :)

2022-08-09 22:32 UTC, Merkur39 requested changes
Attendre le merge de https://github.com/cozy/cozy-libs/pull/1793
Il y a eu un raté sur l'image!

2022-08-10 09:36 UTC, Merkur39 commented
@PolariTOON Pourrais tu mettre à jour `cozy-mespapiers-lib` avec cette version https://github.com/cozy/cozy-libs/releases/tag/cozy-mespapiers-lib%401.5.1 :)

Suite à ça BundleMon devrait être plus aimable 🤡

2022-08-10 10:02 UTC, Merkur39 approved these changes
Super, merci! 👍

2022-08-10 10:13 UTC, merged